#tup = ("ram", 'shyam', 'kapil','kabab', "harishyam")

# print(tup[0])
# print(type(tup))
# tup_as_a_list = list(tup)
# tup_as_a_list.append("halal")
# print(tup_as_a_list)
# print(type(tup_as_a_list))

lol = ("Kabab","meh","Huddi","Ram")
print(lol[2])
lol_as_a_list = list(lol)
lol_as_a_list.append("Yessir")
print(lol_as_a_list)
lol_as_a_list.remove("meh")
print(lol_as_a_list)
# lol_as_a_list.sort(lol_as_a_list)
lol_as_a_list.sort()
print(lol_as_a_list)
lol_as_a_list.insert(3,'Sita')
print(lol_as_a_list)
a = tuple(lol_as_a_list)
print(a)